/** @type {import('next').NextConfig} */

/**
 * next.config.mjs — LifeOS
 *
 * Note on PWA: next-pwa uses Webpack plugins internally.
 * Since Next.js 16 uses Turbopack by default, we configure PWA
 * using the headers + manifest approach instead, and fall back to
 * Webpack mode for the production build via the --webpack flag in package.json.
 *
 * The service worker is served from /public/sw.js (auto-generated by next-pwa
 * when built with Webpack mode) or we use a custom self-hosted SW approach.
 *
 * For local dev: service worker is disabled (NODE_ENV=development).
 */

import withPWA from 'next-pwa';

const isDev = process.env.NODE_ENV === 'development';

const pwaConfig = withPWA({
  dest: 'public',
  register: true,
  skipWaiting: true,
  disable: isDev,
  buildExcludes: [/middleware-manifest\.json$/],
  runtimeCaching: [
    {
      // Cache all API responses with network-first strategy (excluding auth routes)
      urlPattern: /^https?:\/\/.*\/api\/(?!auth\/).*/,
      handler: 'NetworkFirst',
      options: {
        cacheName: 'api-cache',
        networkTimeoutSeconds: 5,
        expiration: {
          maxEntries: 50,
          maxAgeSeconds: 5 * 60, // 5 minutes
        },
      },
    },
    {
      // Cache static assets with stale-while-revalidate
      urlPattern: /^https?:\/\/.*\.(js|css|woff2?|png|jpg|svg|ico)$/,
      handler: 'StaleWhileRevalidate',
      options: {
        cacheName: 'static-assets',
        expiration: {
          maxEntries: 100,
          maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
        },
      },
    },
    {
      // Cache all pages (excluding API routes)
      urlPattern: /^https?:\/\/.*?\/(?!api\/).*/,
      handler: 'NetworkFirst',
      options: {
        cacheName: 'pages-cache',
        networkTimeoutSeconds: 10,
        expiration: {
          maxEntries: 50,
          maxAgeSeconds: 24 * 60 * 60, // 24 hours
        },
      },
    },
  ],
});

const nextConfig = {
  // Turbopack config — needed in Next.js 16 to silence the webpack-vs-turbopack warning
  turbopack: {},

  // Proper Next.js 15/16 image configuration
  images: {
    formats: ['image/avif', 'image/webp'],
  },

  // Security headers
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'X-Frame-Options', value: 'DENY' },
          { key: 'X-XSS-Protection', value: '1; mode=block' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
        ],
      },
    ];
  },
};

export default isDev ? nextConfig : pwaConfig(nextConfig);
