/**
 * Challenge Library — Static Constant
 *
 * Why a static constant instead of a DB seed?
 *   - No DB migration required. Deployed instantly.
 *   - The library never changes per-user — it's a shared catalogue.
 *   - Zero DB reads for browsing the library (just filter this array in memory).
 *   - Easy to add/remove challenges in future PRs without writing migrations.
 *
 * When a user "accepts" a challenge, a Challenge document is created in MongoDB
 * that references this library item by `id`. The library itself stays here.
 */

export interface LibraryChallenge {
  id: string;
  title: string;
  category: 'physical' | 'mental' | 'financial' | 'social' | 'creative';
  description: string;
  target_type: 'streak' | 'total_count' | 'milestone';
  target_value: number;
  suggested_pillar: 'money' | 'soul' | 'curiosity';
  suggested_frequency: 'daily' | 'alternate' | '3x_week' | 'weekly';
  suggested_duration: 15 | 30 | 45 | 60 | 90 | 120;
}

export const CHALLENGE_LIBRARY: LibraryChallenge[] = [
  // ─── PHYSICAL — streak ────────────────────────────────────────────────────
  {
    id: 'ph-001',
    title: 'Cold water immersion',
    category: 'physical',
    description: 'End every shower with 2 minutes of cold water for 30 consecutive days. Builds mental toughness and improves circulation.',
    target_type: 'streak',
    target_value: 30,
    suggested_pillar: 'soul',
    suggested_frequency: 'daily',
    suggested_duration: 15,
  },
  {
    id: 'ph-002',
    title: '10,000 steps daily',
    category: 'physical',
    description: 'Walk at least 10,000 steps every day for 90 days. A foundational movement habit that compounds quietly.',
    target_type: 'streak',
    target_value: 90,
    suggested_pillar: 'soul',
    suggested_frequency: 'daily',
    suggested_duration: 30,
  },
  {
    id: 'ph-003',
    title: 'Morning stretch routine',
    category: 'physical',
    description: 'A 10-minute full-body stretch immediately after waking, 30 days straight. Improves flexibility and sets a calm start to the day.',
    target_type: 'streak',
    target_value: 30,
    suggested_pillar: 'soul',
    suggested_frequency: 'daily',
    suggested_duration: 15,
  },
  {
    id: 'ph-004',
    title: 'No-screen gym sessions',
    category: 'physical',
    description: 'Complete 20 gym sessions — phone stays in the locker. Full presence, no distraction.',
    target_type: 'total_count',
    target_value: 20,
    suggested_pillar: 'soul',
    suggested_frequency: '3x_week',
    suggested_duration: 60,
  },
  {
    id: 'ph-005',
    title: 'Weekly long run',
    category: 'physical',
    description: 'Run 8km+ every week for 12 weeks. Build aerobic base and mental resilience.',
    target_type: 'total_count',
    target_value: 12,
    suggested_pillar: 'soul',
    suggested_frequency: 'weekly',
    suggested_duration: 60,
  },
  {
    id: 'ph-006',
    title: 'Run 5km without stopping',
    category: 'physical',
    description: 'Complete a single 5km run without walking or stopping. A milestone many people talk about and few do.',
    target_type: 'milestone',
    target_value: 1,
    suggested_pillar: 'soul',
    suggested_frequency: '3x_week',
    suggested_duration: 45,
  },
  {
    id: 'ph-007',
    title: '100 push-ups in one session',
    category: 'physical',
    description: 'Build to 100 consecutive (or same-session) push-ups. Track your daily training sets.',
    target_type: 'milestone',
    target_value: 1,
    suggested_pillar: 'soul',
    suggested_frequency: 'daily',
    suggested_duration: 15,
  },
  {
    id: 'ph-008',
    title: 'Climb a mountain and reach summit',
    category: 'physical',
    description: 'Plan, train, and summit a mountain. The training sessions lead to the milestone.',
    target_type: 'milestone',
    target_value: 1,
    suggested_pillar: 'soul',
    suggested_frequency: 'weekly',
    suggested_duration: 90,
  },

  // ─── PHYSICAL — total_count ───────────────────────────────────────────────
  {
    id: 'ph-009',
    title: 'Bike 500km total',
    category: 'physical',
    description: 'Accumulate 500km on the bike over any time period. Log each ride.',
    target_type: 'total_count',
    target_value: 20,
    suggested_pillar: 'soul',
    suggested_frequency: 'alternate',
    suggested_duration: 90,
  },
  {
    id: 'ph-010',
    title: 'Fast for 24 hours',
    category: 'physical',
    description: 'Complete a single 24-hour water fast. One planned milestone that tests discipline.',
    target_type: 'milestone',
    target_value: 1,
    suggested_pillar: 'soul',
    suggested_frequency: 'weekly',
    suggested_duration: 15,
  },

  // ─── MENTAL — streak ──────────────────────────────────────────────────────
  {
    id: 'me-001',
    title: 'Meditate 30 consecutive days',
    category: 'mental',
    description: 'Sit for at least 10 minutes of focused meditation every day. No guided apps — just you and the practice.',
    target_type: 'streak',
    target_value: 30,
    suggested_pillar: 'soul',
    suggested_frequency: 'daily',
    suggested_duration: 15,
  },
  {
    id: 'me-002',
    title: 'Journal every morning for 90 days',
    category: 'mental',
    description: 'Write 3 pages or 15 minutes longhand, first thing. Clears mental noise before the day begins.',
    target_type: 'streak',
    target_value: 90,
    suggested_pillar: 'soul',
    suggested_frequency: 'daily',
    suggested_duration: 15,
  },
  {
    id: 'me-003',
    title: 'Week without social media',
    category: 'mental',
    description: 'Delete all social apps for 7 consecutive days. No browsing on desktop either.',
    target_type: 'streak',
    target_value: 7,
    suggested_pillar: 'soul',
    suggested_frequency: 'daily',
    suggested_duration: 15,
  },
  {
    id: 'me-004',
    title: 'Daily learning session — 30 days',
    category: 'mental',
    description: 'Spend 45 minutes every day studying a subject (not for work). Consistency over intensity.',
    target_type: 'streak',
    target_value: 30,
    suggested_pillar: 'curiosity',
    suggested_frequency: 'daily',
    suggested_duration: 45,
  },

  // ─── MENTAL — total_count ─────────────────────────────────────────────────
  {
    id: 'me-005',
    title: '12 books in a year',
    category: 'mental',
    description: 'Read one book per month — any genre. Log each completion.',
    target_type: 'total_count',
    target_value: 12,
    suggested_pillar: 'curiosity',
    suggested_frequency: 'daily',
    suggested_duration: 30,
  },
  {
    id: 'me-006',
    title: 'Memorize 10 poems',
    category: 'mental',
    description: 'Learn 10 poems by heart — short or long. Improves memory and gives you something to carry.',
    target_type: 'total_count',
    target_value: 10,
    suggested_pillar: 'curiosity',
    suggested_frequency: '3x_week',
    suggested_duration: 30,
  },
  {
    id: 'me-007',
    title: 'Write 52 journal entries',
    category: 'mental',
    description: 'One meaningful journal entry every week for a year. Depth over frequency.',
    target_type: 'total_count',
    target_value: 52,
    suggested_pillar: 'soul',
    suggested_frequency: 'weekly',
    suggested_duration: 30,
  },
  {
    id: 'me-008',
    title: 'Spend a full day alone in silence',
    category: 'mental',
    description: 'No phone, no music, no conversation for one full day. Confronting and clarifying.',
    target_type: 'milestone',
    target_value: 1,
    suggested_pillar: 'soul',
    suggested_frequency: 'weekly',
    suggested_duration: 30,
  },
  {
    id: 'me-009',
    title: 'Complete a 10-day Vipassana',
    category: 'mental',
    description: 'Ten days of silent meditation. Log preparation sessions leading to it.',
    target_type: 'milestone',
    target_value: 1,
    suggested_pillar: 'soul',
    suggested_frequency: 'daily',
    suggested_duration: 60,
  },
  {
    id: 'me-010',
    title: 'Learn a new skill — 50 hours',
    category: 'mental',
    description: 'Deliberately practice one new skill (instrument, language, craft) for 50 total hours.',
    target_type: 'total_count',
    target_value: 50,
    suggested_pillar: 'curiosity',
    suggested_frequency: 'daily',
    suggested_duration: 60,
  },

  // ─── FINANCIAL — streak ───────────────────────────────────────────────────
  {
    id: 'fi-001',
    title: 'Daily finance review — 30 days',
    category: 'financial',
    description: 'Spend 10 minutes every day reviewing your spending, savings, and financial position.',
    target_type: 'streak',
    target_value: 30,
    suggested_pillar: 'money',
    suggested_frequency: 'daily',
    suggested_duration: 15,
  },
  {
    id: 'fi-002',
    title: 'No impulse buys — 21 days',
    category: 'financial',
    description: 'Nothing unplanned for 21 consecutive days. Every purchase is intentional and on budget.',
    target_type: 'streak',
    target_value: 21,
    suggested_pillar: 'money',
    suggested_frequency: 'daily',
    suggested_duration: 15,
  },
  {
    id: 'fi-003',
    title: 'Weekly investment review',
    category: 'financial',
    description: 'Review your portfolio, add to SIP/ETF, and read one financial article every week for 52 weeks.',
    target_type: 'total_count',
    target_value: 52,
    suggested_pillar: 'money',
    suggested_frequency: 'weekly',
    suggested_duration: 30,
  },
  {
    id: 'fi-004',
    title: 'Build a 3-month emergency fund',
    category: 'financial',
    description: 'Track weekly progress toward your emergency fund target. Log each contribution.',
    target_type: 'milestone',
    target_value: 1,
    suggested_pillar: 'money',
    suggested_frequency: 'weekly',
    suggested_duration: 30,
  },
  {
    id: 'fi-005',
    title: 'Read 6 finance/business books',
    category: 'financial',
    description: 'One finance or business book every 2 months — cover to cover.',
    target_type: 'total_count',
    target_value: 6,
    suggested_pillar: 'money',
    suggested_frequency: 'daily',
    suggested_duration: 30,
  },
  {
    id: 'fi-006',
    title: 'Side income — first ₹10,000',
    category: 'financial',
    description: 'Earn your first ₹10,000 from a side project. Log sessions toward it.',
    target_type: 'milestone',
    target_value: 1,
    suggested_pillar: 'money',
    suggested_frequency: 'daily',
    suggested_duration: 60,
  },
  {
    id: 'fi-007',
    title: 'Monthly net worth tracking — 12 months',
    category: 'financial',
    description: 'Update your net worth spreadsheet on the 1st of every month for a full year.',
    target_type: 'total_count',
    target_value: 12,
    suggested_pillar: 'money',
    suggested_frequency: 'weekly',
    suggested_duration: 30,
  },
  {
    id: 'fi-008',
    title: 'No eating out — 30 days',
    category: 'financial',
    description: 'Cook every meal at home for 30 days. Builds discipline and saves money.',
    target_type: 'streak',
    target_value: 30,
    suggested_pillar: 'money',
    suggested_frequency: 'daily',
    suggested_duration: 15,
  },

  // ─── SOCIAL ───────────────────────────────────────────────────────────────
  {
    id: 'so-001',
    title: 'Reconnect with 10 old friends',
    category: 'social',
    description: 'Reach out to 10 people you've lost touch with — a message, call, or coffee.',
    target_type: 'total_count',
    target_value: 10,
    suggested_pillar: 'soul',
    suggested_frequency: 'weekly',
    suggested_duration: 30,
  },
  {
    id: 'so-002',
    title: 'Weekly family call — 6 months',
    category: 'social',
    description: 'A real call (not a message) with a family member every week for 26 weeks.',
    target_type: 'total_count',
    target_value: 26,
    suggested_pillar: 'soul',
    suggested_frequency: 'weekly',
    suggested_duration: 30,
  },
  {
    id: 'so-003',
    title: 'Host a dinner party',
    category: 'social',
    description: 'Plan and cook a full dinner for 6+ people. From menu to dessert.',
    target_type: 'milestone',
    target_value: 1,
    suggested_pillar: 'soul',
    suggested_frequency: 'weekly',
    suggested_duration: 90,
  },
  {
    id: 'so-004',
    title: 'Attend 12 community events',
    category: 'social',
    description: 'One local event (meetup, workshop, community gathering) per month for a year.',
    target_type: 'total_count',
    target_value: 12,
    suggested_pillar: 'soul',
    suggested_frequency: 'weekly',
    suggested_duration: 60,
  },
  {
    id: 'so-005',
    title: 'Daily gratitude — say it out loud',
    category: 'social',
    description: 'Tell one person something you appreciate about them every day for 30 days.',
    target_type: 'streak',
    target_value: 30,
    suggested_pillar: 'soul',
    suggested_frequency: 'daily',
    suggested_duration: 15,
  },
  {
    id: 'so-006',
    title: 'Volunteer 10 times',
    category: 'social',
    description: 'Give time to a cause 10 times over the year. Minimum 2 hours per session.',
    target_type: 'total_count',
    target_value: 10,
    suggested_pillar: 'soul',
    suggested_frequency: 'weekly',
    suggested_duration: 120,
  },
  {
    id: 'so-007',
    title: 'Write a letter to someone',
    category: 'social',
    description: 'Hand-write a letter to someone who has influenced your life. One meaningful action.',
    target_type: 'milestone',
    target_value: 1,
    suggested_pillar: 'soul',
    suggested_frequency: 'weekly',
    suggested_duration: 30,
  },
  {
    id: 'so-008',
    title: 'Meet 1 new person every week',
    category: 'social',
    description: 'Intentionally meet and have a real conversation with someone new every week for 12 weeks.',
    target_type: 'total_count',
    target_value: 12,
    suggested_pillar: 'soul',
    suggested_frequency: 'weekly',
    suggested_duration: 30,
  },

  // ─── CREATIVE ─────────────────────────────────────────────────────────────
  {
    id: 'cr-001',
    title: 'Learn 10 meals from scratch',
    category: 'creative',
    description: 'Cook 10 dishes you've never made before — from raw ingredients, no shortcuts.',
    target_type: 'total_count',
    target_value: 10,
    suggested_pillar: 'soul',
    suggested_frequency: 'weekly',
    suggested_duration: 90,
  },
  {
    id: 'cr-002',
    title: 'Write 30 poems',
    category: 'creative',
    description: 'One poem per day for 30 days. Quantity over perfection — let the habit build the voice.',
    target_type: 'total_count',
    target_value: 30,
    suggested_pillar: 'curiosity',
    suggested_frequency: 'daily',
    suggested_duration: 30,
  },
  {
    id: 'cr-003',
    title: 'Sketch every day — 30 days',
    category: 'creative',
    description: 'Fill one page of a sketchbook every single day for 30 days. Subject is your choice.',
    target_type: 'streak',
    target_value: 30,
    suggested_pillar: 'curiosity',
    suggested_frequency: 'daily',
    suggested_duration: 30,
  },
  {
    id: 'cr-004',
    title: 'Complete a personal project',
    category: 'creative',
    description: 'Finish a creative project you've been putting off — app, essay, painting, anything.',
    target_type: 'milestone',
    target_value: 1,
    suggested_pillar: 'curiosity',
    suggested_frequency: 'daily',
    suggested_duration: 60,
  },
  {
    id: 'cr-005',
    title: 'Photograph one thing daily — 90 days',
    category: 'creative',
    description: 'One intentional photograph per day for 90 days. Trains your eye and attention.',
    target_type: 'streak',
    target_value: 90,
    suggested_pillar: 'curiosity',
    suggested_frequency: 'daily',
    suggested_duration: 15,
  },
  {
    id: 'cr-006',
    title: 'Learn a musical instrument — 50 sessions',
    category: 'creative',
    description: 'Practice an instrument for 30 minutes, 50 times. Progress tracked by sessions not days.',
    target_type: 'total_count',
    target_value: 50,
    suggested_pillar: 'curiosity',
    suggested_frequency: 'daily',
    suggested_duration: 30,
  },
  {
    id: 'cr-007',
    title: 'Publish 12 pieces of writing',
    category: 'creative',
    description: 'Post one essay, article, or piece of writing publicly per month for a year.',
    target_type: 'total_count',
    target_value: 12,
    suggested_pillar: 'curiosity',
    suggested_frequency: 'weekly',
    suggested_duration: 60,
  },
  {
    id: 'cr-008',
    title: 'Build something with your hands',
    category: 'creative',
    description: 'Complete one physical project (furniture, electronics, craft) from start to finish.',
    target_type: 'milestone',
    target_value: 1,
    suggested_pillar: 'curiosity',
    suggested_frequency: 'weekly',
    suggested_duration: 90,
  },
  {
    id: 'cr-009',
    title: 'Write a short story',
    category: 'creative',
    description: 'Complete a short story of at least 2,000 words. One milestone, multiple writing sessions.',
    target_type: 'milestone',
    target_value: 1,
    suggested_pillar: 'curiosity',
    suggested_frequency: 'daily',
    suggested_duration: 45,
  },
  {
    id: 'cr-010',
    title: 'Design something every week — 3 months',
    category: 'creative',
    description: 'Create one visual design (poster, UI, logo, pattern) each week for 12 weeks.',
    target_type: 'total_count',
    target_value: 12,
    suggested_pillar: 'curiosity',
    suggested_frequency: 'weekly',
    suggested_duration: 60,
  },
];
