/**
 * Module — Notebook Tests
 *
 * Covers the full CRUD lifecycle for NotebookTopic and NotebookEntry,
 * testing both the Mongoose model layer and the Zod validators.
 *
 * Like the tasks tests, we exercise DB operations directly rather than
 * mounting the Next.js HTTP stack — this keeps tests fast and avoids
 * mocking NextAuth session in every describe block.
 *
 * Design decisions documented inline (see WHY comments):
 *
 *  entry_count denormalisation
 *    WHY: The topic list renders entry counts for every topic card. Doing a
 *    COUNT query per topic on every list render would be N+1 queries and slow
 *    on mobile. Caching the count on the topic document keeps the list to a
 *    single Collection.find() call.
 *
 *  body 5 000-char DB cap vs 2 000-char UI soft warning
 *    WHY: 5 000 is the hard DB limit (enforced by Mongoose + Zod) to prevent
 *    runaway entries bloating the collection. The UI shows a warning at 2 000
 *    chars to nudge users toward concise notes before they hit the hard wall —
 *    giving them a chance to break the entry into multiple notes.
 *
 *  Cascade delete (topic → entries)
 *    WHY: NotebookEntry documents reference their topic via `topic_id`. If the
 *    topic is hard-deleted without removing its entries, those entries become
 *    orphans: they consume storage, cannot be listed (no topic to navigate to),
 *    and inflate the collection indefinitely. The API performs deleteMany on
 *    entries before deleting the topic to keep the DB clean.
 *
 *  learningsTopicId fetched via SWR not hardcoded
 *    WHY: Topic ObjectIds are generated by MongoDB and differ across every
 *    environment (dev, staging, production, CI). Hardcoding an ID would make
 *    the Save-to-Notebook shortcut work only on the machine where the DB was
 *    seeded. Fetching via SWR at runtime resolves the correct ID for whichever
 *    DB instance is live.
 *
 * Test matrix:
 *   N-1  GET topics → returns seeded topic
 *   N-2  POST topics valid → 201, entry_count: 0
 *   N-3  POST topics missing title → Zod rejects, no DB write
 *   N-4  POST entries valid → 201, entry_count++, last_entry_on updated
 *   N-5  POST entries empty body → Zod rejects
 *   N-6  PATCH entry → body updated
 *   N-7  DELETE entry → removed, topic entry_count decremented
 *   N-8  DELETE topic → topic removed + cascade entries removed
 *   N-9  DELETE nonexistent topic → returns null (API maps to 404)
 */

import mongoose, { Types } from 'mongoose';
import { MongoMemoryServer } from 'mongodb-memory-server';
import NotebookTopic from '@/models/NotebookTopic';
import NotebookEntry from '@/models/NotebookEntry';
import {
  NotebookTopicSchema,
  NotebookEntrySchema,
} from '@/lib/validators/notebook';

// ─── Infrastructure ───────────────────────────────────────────────────────────

let mongoServer: MongoMemoryServer;

beforeAll(async () => {
  mongoServer = await MongoMemoryServer.create();
  await mongoose.connect(mongoServer.getUri());
});

afterAll(async () => {
  await mongoose.disconnect();
  await mongoServer.stop();
});

afterEach(async () => {
  // Wipe both collections between tests to guarantee isolation
  await NotebookEntry.deleteMany({});
  await NotebookTopic.deleteMany({});
});

// ─── Factories ────────────────────────────────────────────────────────────────

const makeTopic = (overrides: Partial<{
  title: string;
  icon: string;
  color: 'amber' | 'blue' | 'rose' | 'emerald' | 'indigo' | 'zinc';
  pinned: boolean;
  active: boolean;
}> = {}) => ({
  title: 'Test Topic',
  icon: '📝',
  color: 'indigo' as const,
  pinned: false,
  active: true,
  ...overrides,
});

const makeEntry = (topicId: Types.ObjectId, overrides: Partial<{
  body: string;
  source: string;
  tags: string[];
}> = {}) => ({
  topic_id: topicId,
  body: 'This is a test learning note.',
  source: 'Test Book',
  tags: ['learning'],
  ...overrides,
});

// ─── N-1: GET topics ──────────────────────────────────────────────────────────

describe('N-1 — GET topics', () => {
  beforeEach(async () => {
    await NotebookTopic.create(makeTopic({ title: 'Test Topic' }));
  });

  it('returns seeded topic in find({ active: true }) query', async () => {
    const topics = await NotebookTopic.find({ active: true })
      .sort({ pinned: -1, last_entry_on: -1 })
      .lean();

    expect(topics).toHaveLength(1);
    expect(topics[0].title).toBe('Test Topic');
    expect(topics[0].entry_count).toBe(0);
    expect(topics[0].last_entry_on).toBeNull();
  });

  it('does not return inactive topics', async () => {
    await NotebookTopic.create(makeTopic({ title: 'Hidden', active: false }));
    const topics = await NotebookTopic.find({ active: true }).lean();
    const titles = topics.map((t) => t.title);
    expect(titles).not.toContain('Hidden');
  });

  it('pins float to the top (sort: pinned DESC)', async () => {
    await NotebookTopic.create(makeTopic({ title: 'Pinned', pinned: true }));

    const topics = await NotebookTopic.find({ active: true })
      .sort({ pinned: -1, last_entry_on: -1 })
      .lean();

    expect(topics[0].title).toBe('Pinned');
  });
});

// ─── N-2: POST topics valid ───────────────────────────────────────────────────

describe('N-2 — POST topics valid → entry_count: 0 on creation', () => {
  /**
   * WHY entry_count starts at 0:
   * entry_count is a denormalised cache field updated on every entry write.
   * A freshly created topic has no entries, so it must start at 0 — never
   * undefined — so the UI can safely render "0 entries" without a null-check.
   */
  it('creates topic with default entry_count=0 and last_entry_on=null', async () => {
    const topic = await NotebookTopic.create(makeTopic());

    expect(topic._id).toBeDefined();
    expect(topic.entry_count).toBe(0);
    expect(topic.last_entry_on).toBeNull();
  });

  it('assigns the provided color', async () => {
    const topic = await NotebookTopic.create(makeTopic({ color: 'amber' }));
    expect(topic.color).toBe('amber');
  });

  it('defaults icon to 📝 when not provided', async () => {
    const topic = await NotebookTopic.create({ title: 'No Icon', color: 'blue' });
    expect(topic.icon).toBe('📝');
  });

  it('defaults pinned=false', async () => {
    const topic = await NotebookTopic.create(makeTopic());
    expect(topic.pinned).toBe(false);
  });
});

// ─── N-3: POST topics missing title ───────────────────────────────────────────

describe('N-3 — POST topics missing / invalid title', () => {
  it('Zod rejects missing title → fieldError on title', () => {
    const result = NotebookTopicSchema.safeParse({
      icon: '📝',
      color: 'indigo',
    });
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.flatten().fieldErrors.title).toBeDefined();
    }
  });

  it('Zod rejects empty title → fieldError on title', () => {
    const result = NotebookTopicSchema.safeParse({
      title: '',
      icon: '📝',
      color: 'indigo',
    });
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.flatten().fieldErrors.title).toBeDefined();
    }
  });

  it('Zod rejects title > 60 chars → fieldError on title', () => {
    const result = NotebookTopicSchema.safeParse({
      title: 't'.repeat(61),
      icon: '📝',
      color: 'indigo',
    });
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.flatten().fieldErrors.title).toBeDefined();
    }
  });

  it('Zod rejects invalid color → fieldError on color', () => {
    const result = NotebookTopicSchema.safeParse({
      title: 'Valid Title',
      icon: '📝',
      color: 'purple', // not in enum
    });
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.flatten().fieldErrors.color).toBeDefined();
    }
  });

  it('Mongoose rejects topic without title → ValidationError (no Zod bypass)', async () => {
    await expect(
      NotebookTopic.create({ icon: '📝', color: 'indigo' })
    ).rejects.toThrow();
  });
});

// ─── N-4: POST entries valid ──────────────────────────────────────────────────

describe('N-4 — POST entries valid → entry_count++ and last_entry_on updated', () => {
  /**
   * The entry creation flow is a two-document atomic update:
   *  1. Create the NotebookEntry.
   *  2. Increment the parent topic's entry_count and set last_entry_on.
   *
   * Both steps are done in Promise.all() in the route handler. Here we test
   * the final state (what the DB looks like after both operations).
   */
  it('entry is created and topic stats are updated', async () => {
    const topic = await NotebookTopic.create(makeTopic());
    const today = new Date().toISOString().split('T')[0];

    // Simulate the route handler's Promise.all
    const [entry] = await Promise.all([
      NotebookEntry.create(makeEntry(topic._id)),
      NotebookTopic.findByIdAndUpdate(
        topic._id,
        { $inc: { entry_count: 1 }, $set: { last_entry_on: today } },
        { new: true }
      ),
    ]);

    expect(entry._id).toBeDefined();
    expect(entry.body).toBe('This is a test learning note.');

    const updatedTopic = await NotebookTopic.findById(topic._id).lean();
    expect(updatedTopic!.entry_count).toBe(1);
    expect(updatedTopic!.last_entry_on).toBe(today);
  });

  it('second entry further increments entry_count to 2', async () => {
    const topic = await NotebookTopic.create(makeTopic());
    const today = new Date().toISOString().split('T')[0];

    for (let i = 0; i < 2; i++) {
      await Promise.all([
        NotebookEntry.create(makeEntry(topic._id, { body: `Note ${i}` })),
        NotebookTopic.findByIdAndUpdate(topic._id, {
          $inc: { entry_count: 1 },
          $set: { last_entry_on: today },
        }),
      ]);
    }

    const updatedTopic = await NotebookTopic.findById(topic._id).lean();
    expect(updatedTopic!.entry_count).toBe(2);
  });

  it('entry stores tags correctly', async () => {
    const topic = await NotebookTopic.create(makeTopic());
    const entry = await NotebookEntry.create(
      makeEntry(topic._id, { tags: ['react', 'hooks', 'performance'] })
    );
    expect(entry.tags).toEqual(['react', 'hooks', 'performance']);
  });
});

// ─── N-5: POST entries empty body ────────────────────────────────────────────

describe('N-5 — POST entries empty body', () => {
  /**
   * WHY two separate limits (5 000 DB cap, 2 000 UI soft warning):
   *
   *  - 5 000 chars is the hard Mongoose + Zod limit. Writing more would create
   *    bloated BSON documents and slow down the entries list query. This cap is
   *    enforced at the DB layer as a last line of defence.
   *
   *  - 2 000 chars is a soft UI warning shown to the user before they hit the
   *    hard wall. It nudges toward concise notes (the "one idea per note"
   *    principle) and gives the user a chance to split the content into multiple
   *    entries rather than receiving a hard validation error at 5 001 chars.
   *
   * Tests below verify the hard boundaries only (Zod + Mongoose).
   * The 2 000-char soft warning is a UI concern tested in component tests.
   */
  it('Zod rejects empty body → fieldError on body', () => {
    const result = NotebookEntrySchema.safeParse({ body: '' });
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.flatten().fieldErrors.body).toBeDefined();
    }
  });

  it('Zod rejects body > 5 000 chars → fieldError on body', () => {
    const result = NotebookEntrySchema.safeParse({ body: 'x'.repeat(5001) });
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.flatten().fieldErrors.body).toBeDefined();
    }
  });

  it('Zod accepts body at exactly 5 000 chars → passes', () => {
    const result = NotebookEntrySchema.safeParse({ body: 'x'.repeat(5000) });
    expect(result.success).toBe(true);
  });

  it('Zod rejects more than 5 tags → fieldError on tags', () => {
    const result = NotebookEntrySchema.safeParse({
      body: 'Valid body',
      tags: ['a', 'b', 'c', 'd', 'e', 'f'],
    });
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.flatten().fieldErrors.tags).toBeDefined();
    }
  });

  it('Mongoose rejects empty body → ValidationError', async () => {
    const topic = await NotebookTopic.create(makeTopic());
    await expect(
      NotebookEntry.create({ topic_id: topic._id, body: '' })
    ).rejects.toThrow();
  });
});

// ─── N-6: PATCH entry ────────────────────────────────────────────────────────

describe('N-6 — PATCH entry → body updated', () => {
  it('updates body and source on an existing entry', async () => {
    const topic = await NotebookTopic.create(makeTopic());
    const entry = await NotebookEntry.create(makeEntry(topic._id));

    const updated = await NotebookEntry.findByIdAndUpdate(
      entry._id,
      { $set: { body: 'Updated body text.', source: 'New Source' } },
      { new: true }
    ).lean();

    expect(updated!.body).toBe('Updated body text.');
    expect(updated!.source).toBe('New Source');
  });

  it('updating non-existent entry → returns null', async () => {
    const fakeId = new mongoose.Types.ObjectId();
    const result = await NotebookEntry.findByIdAndUpdate(
      fakeId,
      { $set: { body: 'x' } },
      { new: true }
    );
    expect(result).toBeNull();
  });

  it('updates tags on entry', async () => {
    const topic = await NotebookTopic.create(makeTopic());
    const entry = await NotebookEntry.create(makeEntry(topic._id));

    const updated = await NotebookEntry.findByIdAndUpdate(
      entry._id,
      { $set: { tags: ['updated', 'tags'] } },
      { new: true }
    ).lean();

    expect(updated!.tags).toEqual(['updated', 'tags']);
  });
});

// ─── N-7: DELETE entry ────────────────────────────────────────────────────────

describe('N-7 — DELETE entry → removed, topic entry_count decremented', () => {
  it('entry is removed from DB and entry_count is decremented', async () => {
    const topic = await NotebookTopic.create(makeTopic({ title: 'My Topic' }));
    const today = new Date().toISOString().split('T')[0];

    // Seed one entry with correct stat
    const entry = await NotebookEntry.create(makeEntry(topic._id));
    await NotebookTopic.findByIdAndUpdate(topic._id, {
      $inc: { entry_count: 1 },
      $set: { last_entry_on: today },
    });

    // Simulate API DELETE: remove entry + decrement counter
    await NotebookEntry.findByIdAndDelete(entry._id);
    await NotebookTopic.findByIdAndUpdate(topic._id, {
      $inc: { entry_count: -1 },
    });

    const deletedEntry = await NotebookEntry.findById(entry._id);
    expect(deletedEntry).toBeNull();

    const updatedTopic = await NotebookTopic.findById(topic._id).lean();
    expect(updatedTopic!.entry_count).toBe(0);
  });

  it('entry_count never goes below 0 (min guard)', async () => {
    const topic = await NotebookTopic.create(makeTopic());

    // Decrement on a topic with entry_count=0 (defensive case)
    await NotebookTopic.findByIdAndUpdate(topic._id, { $inc: { entry_count: -1 } });

    const t = await NotebookTopic.findById(topic._id).lean();
    // MongoDB allows negative increments — this test documents the raw DB behaviour;
    // the API guards against this by checking entry_count > 0 before decrementing.
    expect(t!.entry_count).toBe(-1);
  });
});

// ─── N-8: DELETE topic (cascade) ─────────────────────────────────────────────

describe('N-8 — DELETE topic → cascade-delete entries', () => {
  /**
   * WHY cascade delete:
   * NotebookEntry documents hold a `topic_id` foreign key. If the parent topic
   * is deleted without removing its entries, those documents become orphans —
   * they can never be retrieved (no topic to navigate to) and permanently waste
   * storage. The API performs NotebookEntry.deleteMany({ topic_id }) before
   * deleting the topic to keep the database clean.
   */
  it('deletes topic and all its entries atomically', async () => {
    const topic = await NotebookTopic.create(makeTopic());

    // Create 3 entries for this topic
    await NotebookEntry.create([
      makeEntry(topic._id, { body: 'Entry 1' }),
      makeEntry(topic._id, { body: 'Entry 2' }),
      makeEntry(topic._id, { body: 'Entry 3' }),
    ]);

    // Simulate cascade delete (as performed by the API route)
    await NotebookEntry.deleteMany({ topic_id: topic._id });
    await NotebookTopic.findByIdAndDelete(topic._id);

    // Topic must be gone
    const deletedTopic = await NotebookTopic.findById(topic._id);
    expect(deletedTopic).toBeNull();

    // All 3 orphaned entries must also be gone
    const orphans = await NotebookEntry.find({ topic_id: topic._id }).lean();
    expect(orphans).toHaveLength(0);
  });

  it('entries from OTHER topics are unaffected by cascade', async () => {
    const topicA = await NotebookTopic.create(makeTopic({ title: 'Topic A' }));
    const topicB = await NotebookTopic.create(makeTopic({ title: 'Topic B' }));

    await NotebookEntry.create(makeEntry(topicA._id, { body: 'Entry in A' }));
    await NotebookEntry.create(makeEntry(topicB._id, { body: 'Entry in B' }));

    // Delete topic A with cascade
    await NotebookEntry.deleteMany({ topic_id: topicA._id });
    await NotebookTopic.findByIdAndDelete(topicA._id);

    // Topic B's entry must survive
    const survivingEntries = await NotebookEntry.find({ topic_id: topicB._id }).lean();
    expect(survivingEntries).toHaveLength(1);
    expect(survivingEntries[0].body).toBe('Entry in B');
  });
});

// ─── N-9: DELETE nonexistent topic ───────────────────────────────────────────

describe('N-9 — DELETE nonexistent topic → null (API maps to 404)', () => {
  /**
   * findByIdAndDelete returns null when no document matches the id.
   * The route handler checks for null and returns 404. This test verifies
   * the DB layer returns null so the handler can detect the miss.
   */
  it('findByIdAndDelete on unknown id returns null', async () => {
    const fakeId = new mongoose.Types.ObjectId();
    const result = await NotebookTopic.findByIdAndDelete(fakeId);
    expect(result).toBeNull();
  });

  it('cascade deleteMany on unknown topic_id deletes 0 entries (safe)', async () => {
    const fakeId = new mongoose.Types.ObjectId();
    const result = await NotebookEntry.deleteMany({ topic_id: fakeId });
    expect(result.deletedCount).toBe(0);
  });
});

// ─── Zod Validator Tests — Full Coverage ─────────────────────────────────────

describe('Zod — NotebookTopicSchema', () => {
  const valid = { title: 'My Topic', icon: '📚', color: 'blue' as const };

  it('valid full payload → passes', () => {
    expect(NotebookTopicSchema.safeParse(valid).success).toBe(true);
  });

  it('missing title → fails', () => {
    const result = NotebookTopicSchema.safeParse({ icon: '📝', color: 'blue' });
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.flatten().fieldErrors.title).toBeDefined();
    }
  });

  it('invalid color → fails', () => {
    const result = NotebookTopicSchema.safeParse({ ...valid, color: 'purple' });
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.flatten().fieldErrors.color).toBeDefined();
    }
  });

  it('icon > 4 chars → fails', () => {
    const result = NotebookTopicSchema.safeParse({ ...valid, icon: 'toolong' });
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.flatten().fieldErrors.icon).toBeDefined();
    }
  });

  it('partial schema (for PATCH) accepts only title', () => {
    const result = NotebookTopicSchema.partial().safeParse({ title: 'Updated' });
    expect(result.success).toBe(true);
  });
});

describe('Zod — NotebookEntrySchema', () => {
  const valid = { body: 'A well-formed notebook entry.' };

  it('valid body → passes', () => {
    expect(NotebookEntrySchema.safeParse(valid).success).toBe(true);
  });

  it('empty body → fails', () => {
    const result = NotebookEntrySchema.safeParse({ body: '' });
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.flatten().fieldErrors.body).toBeDefined();
    }
  });

  it('body exactly at 5 000 chars → passes (hard limit boundary)', () => {
    expect(
      NotebookEntrySchema.safeParse({ body: 'x'.repeat(5000) }).success
    ).toBe(true);
  });

  it('body at 5 001 chars → fails (over hard limit)', () => {
    const result = NotebookEntrySchema.safeParse({ body: 'x'.repeat(5001) });
    expect(result.success).toBe(false);
  });

  it('source > 100 chars → fails', () => {
    const result = NotebookEntrySchema.safeParse({
      ...valid,
      source: 's'.repeat(101),
    });
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.flatten().fieldErrors.source).toBeDefined();
    }
  });

  it('6 tags → fails (max is 5)', () => {
    const result = NotebookEntrySchema.safeParse({
      ...valid,
      tags: ['a', 'b', 'c', 'd', 'e', 'f'],
    });
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.flatten().fieldErrors.tags).toBeDefined();
    }
  });

  it('5 tags → passes', () => {
    expect(
      NotebookEntrySchema.safeParse({ ...valid, tags: ['a', 'b', 'c', 'd', 'e'] }).success
    ).toBe(true);
  });

  it('source and tags optional — only body required', () => {
    expect(NotebookEntrySchema.safeParse({ body: 'Just a body.' }).success).toBe(true);
  });
});
